project_name: app
release:
  github:
    owner: owner
    name: repo
before:
  hooks:
    - go mod download
builds:
  - main: .
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
       - README.md
       - LICENSE
checksum:
  name_template: "{{ .ProjectName }}_{{ .Tag }}_checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-{{ .ShortCommit }}"
